version: '3'

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: test_guru_production
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  web:
    image: colorizemysky/test-guru:latest
    ports:
      - "3001:3000"
    depends_on:
      - db
    environment:
      DATABASE_URL: ${DATABASE_URL}
      RAILS_ENV: production
      RAILS_LOG_TO_STDOUT: true
      SECRET_KEY_BASE: ${SECRET_KEY_BASE}
      RAILS_SERVE_STATIC_FILES: 1
    restart: unless-stopped

volumes:
  postgres_data:
